const products = [
    {
      _id: "1",
      name: "pca ",
      image: "/image/pca.jpg",
      description: "jgrhgrghrghfvhghfhgutuguhguhhrhvhfvhgfhgbuy",
      price: 2100 ,
       countInStock: 4,
      rating: 4,
      numReviews: 3,
    },
    {
      _id: "2",
      name: "pcb ",
      image: "/image/pcb.jpg",
      description: "jgrhgrghrghfvhghfhgutuguhguhhrhvhfvhgfhgbuy",
      price: 1850,
      countInStock: 3,
      rating: 4.5,
      numReviews: 4,
    },
    {
      _id: "3",
      name: "pcc",
      image: "/image/pcc.jpg",
      description: "jgrhgrghrghfvhghfhgutuguhguhhrhvhfvhgfhgbuy",
      price: 2490,
      countInStock: 0,
      rating: 3,
      numReviews: 1,
    },
    {
      _id: "4",
      name: "souris",
      image: "/image/souris.jpg",
      description: "jgrhgrghrghfvhghfhgutuguhguhhrhvhfvhgfhgbuy",
      price:90,
      countInStock: 8,
      rating: 3,
      numReviews: 2,
    },
    {
      _id: "5",
      name: "clavier",
      image: "/image/clavier.jpg",
      description: "jgrhgrghrghfvhghfhgutuguhguhhrhvhfvhgfhgbuy",
      price: 150,
      countInStock: 6,
      rating: 3,
      numReviews: 1,
    },
    {
      _id: "6",
      name: "pc gaming",
      image: "/image/gaming.jpg",
      description: "jgrhgrghrghfvhghfhgutuguhguhhrhvhfvhgfhgbuy",
      price: 3750,
      countInStock: 2,
      rating: 5,
      numReviews: 2,
    },
    {
      _id: "7",
      name: "pc portable",
      image: "/image/portable.jpg",
      description: "jgrhgrghrghfvhghfhgutuguhguhhrhvhfvhgfhgbuy",
      price: 1650,
      countInStock: 5,
      rating: 3,
      numReviews: 1,
    },
    {
      _id: "8",
      name: "pc portale2",
      image: "/image/portable2.jpg",
      description: "jgrhgrghrghfvhghfhgutuguhguhhrhvhfvhgfhgbuy",
      price: 2300,
      countInStock: 4,
      rating: 5,
      numReviews: 2,
    },
  ];
  